node {
    // checkout scmGit(branches: [[name: '*/react-app']], extensions: [], userRemoteConfigs: [[url: '/home/projects/dicoding-submission-jenkins/a428-cicd-labs']])
    withDockerContainer(args: '-p 3000:3000', image: 'node:lts-buster-slim') {
        stage('Build') {
            sh 'npm install'
        }
        stage('Test') {
            sh './jenkins/scripts/test.sh'
        }
        stage('Deliver') {
            sh './jenkins/scripts/deliver.sh'
            input message: 'Finished using the website? (Click "Proceed" to continue)'
            sh './jenkins/scripts/kill.sh'
        }
    }
}
