node {
    withDockerContainer(args: '-p 3000:3000', image: 'node:lts-buster-slim') {
        stage('Build') {
            try {
                sh 'npm install'
            }
            catch (exc) {
                echo 'Something failed when install!'
                throw
            }
        }
        stage('Test') {
            sh './jenkins/scripts/test.sh'
        }
        stage('Deliver') {
            sh './jenkins/scripts/deliver.sh'
            input message: 'Finished using the website? (Click "Proceed" to continue)'
            sh './jenkins/scripts/kill.sh'
        }
    }
}
